title: Saptarshi Ghosh Dastidar
logo: https://github.com/Saptarshighoshdastidar/Saptarshighoshdastidar.github.io/blob/main/Portfolio%20photo.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
